namespace LuaScript.Api
{
    [LuaTable("math")]
    [LuaBuiltin("abs", "x")]
    [LuaBuiltin("ceil", "x")]
    [LuaBuiltin("cos", "x")]
    [LuaBuiltin("exp", "x")]
    [LuaBuiltin("floor", "x")]
    [LuaBuiltin("fmod", "x", "y")]
    [LuaVariable("huge")]
    [LuaBuiltin("log", "x", "base")]
    [LuaBuiltin("max", "x", "...")]
    [LuaBuiltin("min", "x", "...")]
    [LuaBuiltin("modf", "x")]
    [LuaVariable("pi")]
    [LuaBuiltin("random", "m", "n")]
    [LuaBuiltin("randomseed", "x")]
    [LuaBuiltin("sin", "x")]
    [LuaBuiltin("sqrt", "x")]
    [LuaBuiltin("tan", "x")]
    [LuaBuiltin("atan", "y", "x")]
    [LuaBuiltin("atan2", "y", "x")]
    [LuaBuiltin("deg", "x")]
    [LuaBuiltin("rad", "x")]
    [LuaBuiltin("ldexp", "m", "e")]
    [LuaBuiltin("frexp", "x")]
    [LuaBuiltin("sinh", "x")]
    [LuaBuiltin("cosh", "x")]
    [LuaBuiltin("tanh", "x")]
    [LuaBuiltin("type", "x")]
    [LuaBuiltin("tointeger", "x")]
    [LuaVariable("maxinteger")]
    [LuaVariable("mininteger")]
    internal static class LuaMathLibrary;
}
