<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>1.20.1</Version>
		<Platforms>AnyCPU;x64</Platforms>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="LuaScript" />
		<InternalsVisibleTo Include="LuaScript.Tests" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LuaScript.Runtime\LuaScript.Runtime.csproj" />
		<ProjectReference Include="..\LuaScript.Generator\LuaScript.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
		<AdditionalFiles Include="Shaders\*.hlsl" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="SharpGen.Runtime">
			<HintPath>$(YMM4DirPath)SharpGen.Runtime.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.Direct3D11">
			<HintPath>$(YMM4DirPath)Vortice.Direct3D11.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.DirectX">
			<HintPath>$(YMM4DirPath)Vortice.DirectX.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.D3DCompiler.dll">
			<HintPath>$(YMM4DirPath)Vortice.D3DCompiler.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.DXGI.dll">
			<HintPath>$(YMM4DirPath)Vortice.DXGI.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.Mathematics">
			<HintPath>$(YMM4DirPath)Vortice.Mathematics.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>
