<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MoonSharp" Version="2.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LuaScript.Kernel\LuaScript.Kernel.csproj" />
    <ProjectReference Include="..\LuaScript.Compat\LuaScript.Compat.csproj" />
    <ProjectReference Include="..\LuaScript.Runtime\LuaScript.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\native\**" CopyToOutputDirectory="PreserveNewest" LinkBase="native" />
  </ItemGroup>

</Project>
