<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>1.19.1</Version>
		<Platforms>AnyCPU;x64</Platforms>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="LuaScript" />
		<InternalsVisibleTo Include="LuaScript.Compat" />
		<InternalsVisibleTo Include="LuaScript.Runtime" />
		<InternalsVisibleTo Include="LuaScript.Tests" />
	</ItemGroup>

</Project>
