<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>1.16.2</Version>
		<Platforms>AnyCPU;x64</Platforms>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="LuaScript" />
		<InternalsVisibleTo Include="LuaScript.Tests" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="SharpGen.Runtime">
			<HintPath>$(YMM4DirPath)SharpGen.Runtime.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="SharpGen.Runtime.COM">
			<HintPath>$(YMM4DirPath)SharpGen.Runtime.COM.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.Direct2D1">
			<HintPath>$(YMM4DirPath)Vortice.Direct2D1.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.DirectX">
			<HintPath>$(YMM4DirPath)Vortice.DirectX.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.DXGI.dll">
			<HintPath>$(YMM4DirPath)Vortice.DXGI.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.Mathematics">
			<HintPath>$(YMM4DirPath)Vortice.Mathematics.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Vortice.MediaFoundation">
			<HintPath>$(YMM4DirPath)Vortice.MediaFoundation.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

</Project>
