<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Version>1.19.1</Version>
		<Platforms>AnyCPU;x64</Platforms>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="LuaScript" />
		<InternalsVisibleTo Include="LuaScript.Tests" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LuaScript.Kernel\LuaScript.Kernel.csproj" />
		<ProjectReference Include="..\LuaScript.Compat\LuaScript.Compat.csproj" />
		<ProjectReference Include="..\LuaScript.Generator\LuaScript.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MoonSharp" Version="2.0.0" />
	</ItemGroup>

</Project>
